Repository wecode-bootcamp-korea/49-3rd-OneMore-frontend, pull requests merged in 2023-10, with the labels that each got.

#2 [fix]리뷰반영
  src/Router.js
  src/index.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#5 Components/RoutineThumbNail 리뷰 반영 완료
  src/components/RoutineThumbNail/RoutineThumbNail.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#3 [style] layout 리뷰반영
  src/Router.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
  src/styles/Layout.js
Labels: 멘토 리뷰 요청

#13 [fix] main컴포넌트 export오류 수정
  src/pages/Main/Main.js
Labels: 도움 요청, 멘토 리뷰 요청

#14 [feat] Component/checkbox 수정 + theme.js 색상 추가
  src/components/CheckBox/CheckBox.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#16 [style] main-container 추가
  src/Router.js
  src/styles/Layout.js
  src/styles/MainContainer.js
Labels: 멘토 리뷰 요청

#10 [feat] component/button 추가
  src/components/Button/Button.js
Labels: 멘토 리뷰 요청

#19 Component/swiper 리뷰반영 완료
  package-lock.json
  package.json
  public/data/gyeongjae.json
  public/images/다람쥐.jfif
  src/components/Swiper/Swiper.js
  src/config.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#11 [fix] conflict 수정 및 nav ui수정
  src/Router.js
  src/components/Header/Header.js
  src/components/Header/Nav/Nav.js
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
Labels: 수정 요청

#18 Tab컴포넌트 완성
  src/Router.js
  src/components/Tab/Tab.js
Labels: 멘토 리뷰 요청

#20 Components/today routine - 에러 수정
  src/components/TodayRoutine/TodayRoutine.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#21 [feat] Component/checkbox - 체크박스 content 추가
  package-lock.json
  package.json
  src/components/CheckBox/CheckBox.js
Labels: 멘토 리뷰 요청

#23 [style] component/button - border-radius shape 추가
  package-lock.json
  package.json
  src/components/Button/Button.js
Labels: 멘토 리뷰 요청

#30 [style] border, background 수정
  src/components/Button/Button.js
Labels: 멘토 리뷰 요청

#31 [style] background-color 추가, border-color 수정
  src/components/Input/Input.js
Labels: 멘토 리뷰 요청

#25 [feat] feature/login
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Oauth/Oauth.js
Labels: 멘토 리뷰 요청

#26 Page/main 구현완료
  public/data/getTodayRoutine.json
  public/data/postTodayRoutine.json
  public/index.html
  src/components/Swiper/Swiper.js
  src/components/Tab/Tab.js
  src/components/TodayRoutine/TodayRoutine.js
  src/config.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#32 [feat] component/iconbutton
  public/images/icon_berger.png
  public/images/icon_google.png
  public/images/icon_kakao.png
  public/images/icon_naver.png
  public/images/icon_play.png
  src/components/IconButton/IconButton.js
Labels: 멘토 리뷰 요청

#34 [feat] component/backbutton
  public/images/icon_back.png
  src/components/PrevButton/PrevButton.js
Labels: 멘토 리뷰 요청

#35 Page/notHaveRoutine (커스텀 운동이 없을때 나오는 페이지 구현 완료)
  public/data/gyeongjae.json
  public/images/NotHaveRoutine.png
  src/Router.js
  src/components/ExerciseCard/ExerciseCard.js
  src/components/Modal/Modal.js
  src/components/Swiper/Swiper.js
  src/config.js
  src/pages/ExerciseStart.js
  src/pages/Main/Main.js
  src/pages/NotHaveRoutine.js
Labels: 멘토 리뷰 요청

#24 [feat] complete컴포넌트 구현
  src/pages/Completed/Completed.js
  src/pages/Main/Main.js
Labels: Conflict 해결 요청, 수정 요청

#22 [feat] Feature/signup
  src/Router.js
  src/pages/Signup/Signup.js
  src/pages/Signup/SignupTerms.js
Labels: 멘토 리뷰 요청

#29 Pages/exercise start 통신 완료
  public/data/gyeongjae.json
  src/components/ExerciseCard/ExerciseCard.js
  src/components/Swiper/Swiper.js
  src/pages/ExerciseStart.js
Labels: 멘토 리뷰 요청
